### PR TITLE
Fixes #147 (Empty commit for placeholder PR)

### LINKED ISSUE #147: Develop Airdrop dApp
Introduction: Dropzone is a simply web-interface for conducting crypto airdrops. This tasks involves combining the smart contracts with the design which components can be pulled from the UI Kit. The smart contracts are not finalised and solely serve to act as the building blocks for this use case.

Resources:
general - https://files.mybit.io/files/
design - https://www.dropbox.com/s/pz8kdqwxqs6841b/MyBit-Dropzone-Micro-dApp %281%29.zip?dl=0
UI Kit - ui.mybit.io
MyBit SDK - developer.mybit.io
Smart Contracts - https://github.com/MyBitFoundation/MyBit-Dropzone.tech

Requirements of dApp:
1. Force metamask login
2. Enter amount of ETH and select recipient from dropdown. Initial dropdown will be for top 100 ETH addresses (this must be added to the smart contracts)
3. receive airdrops should be removed from design
4. airdrop tokens should be combined with sent airdrops and labeled sent airdrops and be a transaction ledger of sent airdrops.

To submit please initiate a pull request.

Disclaimer:
All work completed via the MyBit Decentralised Development Fund is property of the MyBit Foundation (CHE-177.186.963) and may be used, re-used, and/or distributed, re-distributed by the MyBit Foundation for financial gain. The contributor holds no warrant nor claims for any future payments resulting from monetisation schemes originating from the MyBit Foundation or any of its affiliates. Where law permits outside of open source regulations, the contributor is not permitted to distribute any work completed via the MyBit Decentralised Development Fund (DDF) for personal gain.

### PR DESCRIPTION
**Pull request by pacamara**
Fixes #147 - Develop Airdrop dApp

Placeholder PR so fix for this issue shows up on Status Open Bounty. Since PR is against a different project, would not otherwise be detected.

Actual fix is at MyBitFoundation/MyBit-Dropzone.tech#4

### CODE REVIEW

**Comment by jjperezaguinaga** [comment]
@pacamara Thank you! Taking a look at the other repository now.

**Comment by jjperezaguinaga** [comment]
@pacamara Thank you for your work! Payments should be going now ☺️

**Comment by pacamara** [comment]
@jjperezaguinaga You're welcome, and thank you too! :beers: 
But, payment hasn't gone out yet, the bounty is still on that intermediate "Payment pending maintainer confirmation" stage. It needs that extra confirmation! :smile:

**Comment by jjperezaguinaga** [comment]
We had a bit of an issue with Open Bounty, but we back on track now. Payment should had gone through by now, thanks again!

**Pull request merged**
